### ISSUE TITLE
Correction P4

### ISSUE THREAD

**Issue by lecascyril** [Cerlo/Yacht-Squad-Solidity#1]
"Voici un readme très qualitatif ! La partie smart contract est clairement maîtrisé avec une belle connaissance des SFTs, ça manque cependant de Natspecs. Les scripts sont tout à fait pertinents et font gagner du temps afin de ""remplir d'informations"" le contrat. Très beaux tests. Pour la partie front, c'est très très light, on sent que tu n'as pas réussi à aller jusqu'au bout et que tu as eu des difficultés pour apprendre ReactJS en temps et en heure.
5,5"

**Comment by Cerlo** [comment]
Merci pur ce retour et pour le temps que vous avez pris pour le corriger. Je vais prendre en compte ce que tu m'as dit et ce que le jury m'a dit vis-à-vis de la sécurité (les tableaux de uint des batchs transfert etc ... ).
